baseURL = 'https://blog.tikadata.com/'
languageCode = 'en-us'
title = 'TikaData - AI-powered bookkeeping and financial operation software'
theme = 'ananke'

# Disable theme's header to use our custom header
disableKinds = ["taxonomy", "taxonomyTerm"]

# Markup settings for Table of Contents
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1

  [languages.id]
    contentDir = 'content/id'
    languageName = 'Bahasa Indonesia'
    weight = 2
